Repository jgardona/mhv, pull requests merged in 2023-11, with the labels that each got.

#8 Milestone 2.0
  Cargo.toml
Labels: enhancement

#10 Remove | character output
  src/cli/view.rs
  tests/integrations.rs
Labels: enhancement

#11 Squeezeng feature implementation
  src/cli.rs
  src/cli/view.rs
  tests/data/data3
  tests/data/data4
  tests/data/data5
  tests/integrations.rs
Labels: enhancement

#12 Fix missing documentation in --no-squeezing command.
  src/cli.rs
Labels: bug

#17 Byte units feature
  src/cli.rs
  src/cli/fs.rs
Labels: enhancement

#18 Remove to_string() in main function
  src/main.rs
Labels: enhancement

#19 Enhance documentation
  README.md
  images/demo.png
  images/read1kb.png
  images/read32fromstart.png
  images/read5.png
  images/skip16andread40.png
Labels: documentation

#24 Ref: Use owo colors
  Cargo.toml
  src/cli.rs
  src/cli/view.rs
  tests/data/data1kb
  tests/data/data1mb
  tests/data/data6
  tests/integrations.rs
Labels: refactioring

#29 Opinionated 0x00 / 0xFF changes
  src/cli/view.rs
Labels: bug, enhancement

#32 Update Documentation
  README.md
  images/mhv-dataflow.png
Labels: documentation

#42 More Human Errors
  src/cli.rs
  src/cli/errors.rs
  src/main.rs
  tests/integrations.rs
Labels: enhancement

#43 doc/update for 030
  README.md
  images/demo.png
  images/off0x50-32bytes.png
  images/read1kb.png
  images/read32fromstart.png
  images/read5.png
  images/readutf16.png
  images/skip16andread40.png
Labels: documentation

#45 Update version
  Cargo.toml
Labels: documentation
